/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_TUTORIAL_PROTO_FILES_TEST_PB_H_INCLUDED
#define PB_TUTORIAL_PROTO_FILES_TEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _tutorial_Person_PhoneType {
    tutorial_Person_PhoneType_MOBILE = 0,
    tutorial_Person_PhoneType_HOME = 1,
    tutorial_Person_PhoneType_WORK = 2
} tutorial_Person_PhoneType;

/* Struct definitions */
typedef struct _tutorial_AddressBook {
    pb_callback_t people;
} tutorial_AddressBook;

typedef struct _tutorial_Person {
    pb_callback_t name;
    int32_t id;
    pb_callback_t email;
    pb_callback_t phones;
} tutorial_Person;

typedef struct _tutorial_Person_PhoneNumber {
    pb_callback_t number;
    bool has_type;
    tutorial_Person_PhoneType type;
} tutorial_Person_PhoneNumber;


/* Helper constants for enums */
#define _tutorial_Person_PhoneType_MIN tutorial_Person_PhoneType_MOBILE
#define _tutorial_Person_PhoneType_MAX tutorial_Person_PhoneType_WORK
#define _tutorial_Person_PhoneType_ARRAYSIZE ((tutorial_Person_PhoneType)(tutorial_Person_PhoneType_WORK+1))


/* Initializer values for message structs */
#define tutorial_Person_init_default             {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define tutorial_Person_PhoneNumber_init_default {{{NULL}, NULL}, false, tutorial_Person_PhoneType_HOME}
#define tutorial_AddressBook_init_default        {{{NULL}, NULL}}
#define tutorial_Person_init_zero                {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define tutorial_Person_PhoneNumber_init_zero    {{{NULL}, NULL}, false, _tutorial_Person_PhoneType_MIN}
#define tutorial_AddressBook_init_zero           {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define tutorial_AddressBook_people_tag          1
#define tutorial_Person_name_tag                 1
#define tutorial_Person_id_tag                   2
#define tutorial_Person_email_tag                3
#define tutorial_Person_phones_tag               4
#define tutorial_Person_PhoneNumber_number_tag   1
#define tutorial_Person_PhoneNumber_type_tag     2

/* Struct field encoding specification for nanopb */
#define tutorial_Person_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   name,              1) \
X(a, STATIC,   REQUIRED, INT32,    id,                2) \
X(a, CALLBACK, OPTIONAL, STRING,   email,             3) \
X(a, CALLBACK, REPEATED, MESSAGE,  phones,            4)
#define tutorial_Person_CALLBACK pb_default_field_callback
#define tutorial_Person_DEFAULT NULL
#define tutorial_Person_phones_MSGTYPE tutorial_Person_PhoneNumber

#define tutorial_Person_PhoneNumber_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   number,            1) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              2)
#define tutorial_Person_PhoneNumber_CALLBACK pb_default_field_callback
#define tutorial_Person_PhoneNumber_DEFAULT (const pb_byte_t*)"\x10\x01\x00"

#define tutorial_AddressBook_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  people,            1)
#define tutorial_AddressBook_CALLBACK pb_default_field_callback
#define tutorial_AddressBook_DEFAULT NULL
#define tutorial_AddressBook_people_MSGTYPE tutorial_Person

extern const pb_msgdesc_t tutorial_Person_msg;
extern const pb_msgdesc_t tutorial_Person_PhoneNumber_msg;
extern const pb_msgdesc_t tutorial_AddressBook_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define tutorial_Person_fields &tutorial_Person_msg
#define tutorial_Person_PhoneNumber_fields &tutorial_Person_PhoneNumber_msg
#define tutorial_AddressBook_fields &tutorial_AddressBook_msg

/* Maximum encoded size of messages (where known) */
/* tutorial_Person_size depends on runtime parameters */
/* tutorial_Person_PhoneNumber_size depends on runtime parameters */
/* tutorial_AddressBook_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
